### ISSUE TITLE
el codigo de adolfo tiene el json con mala sintaxis

### ISSUE THREAD

**Issue by antoniogonzalezwebmaster** [antoniogonzalezwebmaster/learninggit#3]
No corre en mi ambiente por error de sintaxis

**Comment by IngeAdolff** [comment]
El problema se corrigió agregando la coma para separar a los participantes.
![image](https://github.com/antoniogonzalezwebmaster/learninggit/assets/135190491/7deb269c-f1d3-4554-aec6-b4423b96e53a)
![image](https://github.com/antoniogonzalezwebmaster/learninggit/assets/135190491/391aa41a-dd8c-4197-b29d-a4f8ff3ed9b5)
